### ISSUE TITLE
Request: support spaces in phone numbers

### ISSUE THREAD

**Issue by chrisdostert** [react-ninja/react-text-format#2]
This is just a feature request to support spaces in phone numbers such as `(206) 782-8410`

Currently this is not picked up as a phone number because of the space

**Comment by ahsan-bilal-786** [comment]
Hi @chrisdostert , 

We have incorporated few more formats for phone numbers The new formats are as following

 123.456.7890 
  2125551212 
 (212) 555 1212 
 (212) 555-1212 
 212-555-1212 ext. 101 
 212 555 1212 x101 

Please take a look into the documentation for further details/examples.

Cheers!

**Comment by chrisdostert** [comment]
@ahsan-bilal-786 this is awesome! thanks
